<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Coin;

class CoinSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $coins = [
            [
                'symbol' => 'BTC',
                'name' => 'Bitcoin',
                'full_name' => 'Bitcoin (BTC)',
                'description' => 'Bitcoin is a decentralized digital currency, without a central bank or single administrator.',
                'current_price' => 43250.75,
                'market_cap' => 847000000000,
                'volume_24h' => 15420000000,
                'price_change_24h' => 1250.75,
                'price_change_percentage_24h' => 2.98,
                'market_cap_rank' => 1,
                'circulating_supply' => 19600000,
                'total_supply' => 19600000,
                'max_supply' => 21000000,
                'is_hot' => true,
                'category' => 'Currency',
                'blockchain' => 'Bitcoin',
                'tags' => ['Store of Value', 'Digital Gold', 'P2P'],
                'launched_at' => '2009-01-03',
            ],
            [
                'symbol' => 'ETH',
                'name' => 'Ethereum',
                'full_name' => 'Ethereum (ETH)',
                'description' => 'Ethereum is a decentralized platform that runs smart contracts.',
                'current_price' => 2650.40,
                'market_cap' => 318000000000,
                'volume_24h' => 8750000000,
                'price_change_24h' => 85.40,
                'price_change_percentage_24h' => 3.33,
                'market_cap_rank' => 2,
                'circulating_supply' => 120000000,
                'total_supply' => 120000000,
                'max_supply' => null,
                'is_hot' => true,
                'category' => 'Smart Contract Platform',
                'blockchain' => 'Ethereum',
                'tags' => ['Smart Contracts', 'DeFi', 'NFTs'],
                'launched_at' => '2015-07-30',
            ],
            [
                'symbol' => 'USDT',
                'name' => 'Tether',
                'full_name' => 'Tether USD (USDT)',
                'description' => 'Tether is a stablecoin pegged to the US Dollar.',
                'current_price' => 1.00,
                'market_cap' => 91000000000,
                'volume_24h' => 25000000000,
                'price_change_24h' => 0.001,
                'price_change_percentage_24h' => 0.01,
                'market_cap_rank' => 3,
                'circulating_supply' => 91000000000,
                'total_supply' => 91000000000,
                'max_supply' => null,
                'category' => 'Stablecoin',
                'blockchain' => 'Multiple',
                'tags' => ['Stablecoin', 'Trading'],
                'launched_at' => '2014-10-06',
            ],
            [
                'symbol' => 'BNB',
                'name' => 'BNB',
                'full_name' => 'BNB (BNB)',
                'description' => 'BNB is the native token of Binance Smart Chain.',
                'current_price' => 315.20,
                'market_cap' => 47000000000,
                'volume_24h' => 1200000000,
                'price_change_24h' => 12.80,
                'price_change_percentage_24h' => 4.23,
                'market_cap_rank' => 4,
                'circulating_supply' => 149000000,
                'total_supply' => 149000000,
                'max_supply' => 200000000,
                'is_hot' => true,
                'category' => 'Exchange Token',
                'blockchain' => 'BSC',
                'tags' => ['Exchange', 'DeFi', 'Ecosystem'],
                'launched_at' => '2017-07-08',
            ],
            [
                'symbol' => 'SOL',
                'name' => 'Solana',
                'full_name' => 'Solana (SOL)',
                'description' => 'Solana is a high-performance blockchain supporting builders around the world.',
                'current_price' => 105.75,
                'market_cap' => 45000000000,
                'volume_24h' => 2100000000,
                'price_change_24h' => 8.25,
                'price_change_percentage_24h' => 8.47,
                'market_cap_rank' => 5,
                'circulating_supply' => 425000000,
                'total_supply' => 507000000,
                'max_supply' => null,
                'is_hot' => true,
                'is_trending' => true,
                'category' => 'Smart Contract Platform',
                'blockchain' => 'Solana',
                'tags' => ['High Performance', 'DeFi', 'NFTs'],
                'launched_at' => '2020-03-16',
            ],
            [
                'symbol' => 'XRP',
                'name' => 'XRP',
                'full_name' => 'XRP (XRP)',
                'description' => 'XRP is a digital asset built for payments.',
                'current_price' => 0.62,
                'market_cap' => 33000000000,
                'volume_24h' => 1800000000,
                'price_change_24h' => 0.045,
                'price_change_percentage_24h' => 7.83,
                'market_cap_rank' => 6,
                'circulating_supply' => 53000000000,
                'total_supply' => 99990000000,
                'max_supply' => 100000000000,
                'category' => 'Payments',
                'blockchain' => 'XRP Ledger',
                'tags' => ['Payments', 'Cross-border'],
                'launched_at' => '2012-06-01',
            ],
            [
                'symbol' => 'ADA',
                'name' => 'Cardano',
                'full_name' => 'Cardano (ADA)',
                'description' => 'Cardano is a blockchain platform for changemakers, innovators, and visionaries.',
                'current_price' => 0.48,
                'market_cap' => 17000000000,
                'volume_24h' => 420000000,
                'price_change_24h' => 0.023,
                'price_change_percentage_24h' => 5.02,
                'market_cap_rank' => 7,
                'circulating_supply' => 35000000000,
                'total_supply' => 45000000000,
                'max_supply' => 45000000000,
                'category' => 'Smart Contract Platform',
                'blockchain' => 'Cardano',
                'tags' => ['Proof of Stake', 'Academic'],
                'launched_at' => '2017-09-29',
            ],
            [
                'symbol' => 'DOGE',
                'name' => 'Dogecoin',
                'full_name' => 'Dogecoin (DOGE)',
                'description' => 'Dogecoin is a cryptocurrency featuring a Shiba Inu from the "Doge" meme.',
                'current_price' => 0.092,
                'market_cap' => 13200000000,
                'volume_24h' => 680000000,
                'price_change_24h' => 0.008,
                'price_change_percentage_24h' => 9.52,
                'market_cap_rank' => 8,
                'circulating_supply' => 143000000000,
                'total_supply' => 143000000000,
                'max_supply' => null,
                'is_trending' => true,
                'category' => 'Meme',
                'blockchain' => 'Dogecoin',
                'tags' => ['Meme', 'Community'],
                'launched_at' => '2013-12-06',
            ],
            [
                'symbol' => 'MATIC',
                'name' => 'Polygon',
                'full_name' => 'Polygon (MATIC)',
                'description' => 'Polygon is a decentralized platform for Ethereum scaling and infrastructure development.',
                'current_price' => 0.87,
                'market_cap' => 8100000000,
                'volume_24h' => 320000000,
                'price_change_24h' => 0.065,
                'price_change_percentage_24h' => 8.07,
                'market_cap_rank' => 9,
                'circulating_supply' => 9300000000,
                'total_supply' => 10000000000,
                'max_supply' => 10000000000,
                'is_new' => true,
                'category' => 'Layer 2',
                'blockchain' => 'Polygon',
                'tags' => ['Scaling', 'Ethereum', 'Layer 2'],
                'launched_at' => '2017-10-01',
            ],
            [
                'symbol' => 'DOT',
                'name' => 'Polkadot',
                'full_name' => 'Polkadot (DOT)',
                'description' => 'Polkadot enables cross-blockchain transfers of any type of data or asset.',
                'current_price' => 7.23,
                'market_cap' => 9200000000,
                'volume_24h' => 180000000,
                'price_change_24h' => 0.34,
                'price_change_percentage_24h' => 4.93,
                'market_cap_rank' => 10,
                'circulating_supply' => 1270000000,
                'total_supply' => 1410000000,
                'max_supply' => null,
                'category' => 'Interoperability',
                'blockchain' => 'Polkadot',
                'tags' => ['Interoperability', 'Parachain'],
                'launched_at' => '2020-08-19',
            ],
        ];

        foreach ($coins as $coinData) {
            Coin::create($coinData);
        }
    }
}
