<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Market;

class MarketSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $markets = [
            [
                'symbol' => 'BTCUSDT',
                'base_currency' => 'BTC',
                'quote_currency' => 'USDT',
                'display_name' => 'Bitcoin/USDT',
                'current_price' => 43250.75,
                'price_change_24h' => 1250.75,
                'price_change_percentage_24h' => 2.98,
                'high_24h' => 44120.50,
                'low_24h' => 41890.25,
                'volume_24h' => 15420000000,
                'min_order_amount' => 0.00001,
                'max_order_amount' => 1000,
                'price_precision' => 2,
                'quantity_precision' => 5,
            ],
            [
                'symbol' => 'ETHUSDT',
                'base_currency' => 'ETH',
                'quote_currency' => 'USDT',
                'display_name' => 'Ethereum/USDT',
                'current_price' => 2650.40,
                'price_change_24h' => 85.40,
                'price_change_percentage_24h' => 3.33,
                'high_24h' => 2720.80,
                'low_24h' => 2540.20,
                'volume_24h' => 8750000000,
                'min_order_amount' => 0.0001,
                'max_order_amount' => 10000,
                'price_precision' => 2,
                'quantity_precision' => 4,
            ],
            [
                'symbol' => 'BNBUSDT',
                'base_currency' => 'BNB',
                'quote_currency' => 'USDT',
                'display_name' => 'BNB/USDT',
                'current_price' => 315.20,
                'price_change_24h' => 12.80,
                'price_change_percentage_24h' => 4.23,
                'high_24h' => 325.50,
                'low_24h' => 302.40,
                'volume_24h' => 1200000000,
                'min_order_amount' => 0.001,
                'max_order_amount' => 50000,
                'price_precision' => 2,
                'quantity_precision' => 3,
            ],
            [
                'symbol' => 'SOLUSDT',
                'base_currency' => 'SOL',
                'quote_currency' => 'USDT',
                'display_name' => 'Solana/USDT',
                'current_price' => 105.75,
                'price_change_24h' => 8.25,
                'price_change_percentage_24h' => 8.47,
                'high_24h' => 112.30,
                'low_24h' => 97.50,
                'volume_24h' => 2100000000,
                'min_order_amount' => 0.01,
                'max_order_amount' => 100000,
                'price_precision' => 2,
                'quantity_precision' => 2,
            ],
            [
                'symbol' => 'XRPUSDT',
                'base_currency' => 'XRP',
                'quote_currency' => 'USDT',
                'display_name' => 'XRP/USDT',
                'current_price' => 0.62,
                'price_change_24h' => 0.045,
                'price_change_percentage_24h' => 7.83,
                'high_24h' => 0.655,
                'low_24h' => 0.575,
                'volume_24h' => 1800000000,
                'min_order_amount' => 1,
                'max_order_amount' => 1000000,
                'price_precision' => 4,
                'quantity_precision' => 1,
            ],
            [
                'symbol' => 'ADAUSDT',
                'base_currency' => 'ADA',
                'quote_currency' => 'USDT',
                'display_name' => 'Cardano/USDT',
                'current_price' => 0.48,
                'price_change_24h' => 0.023,
                'price_change_percentage_24h' => 5.02,
                'high_24h' => 0.495,
                'low_24h' => 0.457,
                'volume_24h' => 420000000,
                'min_order_amount' => 1,
                'max_order_amount' => 1000000,
                'price_precision' => 4,
                'quantity_precision' => 1,
            ],
            [
                'symbol' => 'DOGEUSDT',
                'base_currency' => 'DOGE',
                'quote_currency' => 'USDT',
                'display_name' => 'Dogecoin/USDT',
                'current_price' => 0.092,
                'price_change_24h' => 0.008,
                'price_change_percentage_24h' => 9.52,
                'high_24h' => 0.097,
                'low_24h' => 0.084,
                'volume_24h' => 680000000,
                'min_order_amount' => 10,
                'max_order_amount' => 10000000,
                'price_precision' => 5,
                'quantity_precision' => 0,
            ],
            [
                'symbol' => 'MATICUSDT',
                'base_currency' => 'MATIC',
                'quote_currency' => 'USDT',
                'display_name' => 'Polygon/USDT',
                'current_price' => 0.87,
                'price_change_24h' => 0.065,
                'price_change_percentage_24h' => 8.07,
                'high_24h' => 0.92,
                'low_24h' => 0.805,
                'volume_24h' => 320000000,
                'min_order_amount' => 1,
                'max_order_amount' => 1000000,
                'price_precision' => 4,
                'quantity_precision' => 1,
            ],
            [
                'symbol' => 'DOTUSDT',
                'base_currency' => 'DOT',
                'quote_currency' => 'USDT',
                'display_name' => 'Polkadot/USDT',
                'current_price' => 7.23,
                'price_change_24h' => 0.34,
                'price_change_percentage_24h' => 4.93,
                'high_24h' => 7.58,
                'low_24h' => 6.89,
                'volume_24h' => 180000000,
                'min_order_amount' => 0.1,
                'max_order_amount' => 100000,
                'price_precision' => 3,
                'quantity_precision' => 2,
            ],
            // BTC pairs
            [
                'symbol' => 'ETHBTC',
                'base_currency' => 'ETH',
                'quote_currency' => 'BTC',
                'display_name' => 'Ethereum/Bitcoin',
                'current_price' => 0.0613,
                'price_change_24h' => 0.0008,
                'price_change_percentage_24h' => 1.32,
                'high_24h' => 0.0625,
                'low_24h' => 0.0605,
                'volume_24h' => 125000,
                'min_order_amount' => 0.001,
                'max_order_amount' => 10000,
                'price_precision' => 6,
                'quantity_precision' => 3,
            ],
        ];

        foreach ($markets as $marketData) {
            Market::create($marketData);
        }
    }
}
